name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install latest Fastlane
        run: |
          brew update
          brew upgrade fastlane || brew install fastlane
          fastlane --version

      - name: Clear Fastlane session
        run: |
          unset FASTLANE_SESSION
          rm -f /tmp/spaceship_itc_service_key.txt

      - name: Sign
        run: |
          PYTHONUNBUFFERED=1 ./sign.py
